apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wordpress-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wordpress
  policy:
    semver:
      range: 1.0.x

