apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: wordpress
          image: your-registry/wordpress:1.0.0
          imagePullPolicy: Always
